services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env.test
    networks:
      - mynetwork
    depends_on:
      postgres:
        condition: service_healthy

networks:
  mynetwork:
    name: mynetwork