name: Pull Request on GitHub
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Make new a .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_PORT: 5000
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_DB: "cicd_tests"
          envkey_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/cicd_tests"
          directory: .
          file_name: .env.test
      - name: Run tests
        run: docker compose -f docker-compose-test.yml run backend npm run test:ci
